### ISSUE TITLE
Peer dependency update for NextJs 11

### ISSUE THREAD

**Issue by sakkelaaksonen** [yonycalsin/nextjs-cors#59]
Hi there.
Nextjs 11 came out. 
Could you please add peer dependency support for the latest version.
Thanks in advance.

**Comment by notjustinshaw** [comment]
NextJS v11 Upgrade Guide: https://github.com/vercel/next.js/blob/canary/docs/upgrading.md

**Comment by yonycalsin** [comment]
@sakkelaaksonen @justinalexandershaw 🎉  Wow thanks for the notice, I will publish it later as a new version.
