### ISSUE TITLE
Update for Next.js 12

### ISSUE THREAD

**Issue by ghost** [yonycalsin/nextjs-cors#67]
**Is your feature request related to a problem? Please describe.**
Next.js updated to version 12.

**Describe the solution you'd like**
This package to support Next.js 12. I currently get warning messages when using Next.js 12:
`nextjs-cors@2.0.0" has incorrect peer dependency "next@^8.1.1-canary.54 || ^9.0.0 || ^10.0.0 || ^11.0.0".`

**Comment by yonycalsin** [comment]
Resolved in https://github.com/yonycalsin/nextjs-cors/commit/afd9c62a4967ca74d5798f62a17a76e10760cb7a 🎉

**Comment by ghost** [comment]
Awesome, thanks.
