### ISSUE TITLE
Peer dependency update for NextJs 13

### ISSUE THREAD

**Issue by tobiasalthoff** [yonycalsin/nextjs-cors#75]
Next.js 13 is out and nextjs-cors depends on nextjs 12:

> Could not resolve dependency:
npm ERR! peer next@"^8.1.1-canary.54 || ^9.0.0 || ^10.0.0-0 || ^11.0.0 || ^12.0.0" from nextjs-cors@2.1.1

**Comment by yonycalsin** [comment]
Hi @tobiasalthoff, 

the version was updated in [this PR](https://github.com/yonycalsin/nextjs-cors/pull/73), and later today I will release the new version with this change, supporting the next 13.

**Comment by yonycalsin** [comment]
next13 peer dependency support is now available in version 2.1.2.

https://github.com/yonycalsin/nextjs-cors/releases/tag/v2.1.2

**Comment by tobiasalthoff** [comment]
Hey @yonycalsin, thank you! :-)
