### ISSUE TITLE
Updated peer dependences not in a release

### ISSUE THREAD

**Issue by powderham** [yonycalsin/nextjs-cors#79]
The latest push to master to [update peer dependencies](https://github.com/yonycalsin/nextjs-cors/commit/f7ace8956801e0a5e37ee876f5d97db808872a41) has not been put in to a release yet. 

It appears as though it all works fine, are we able to push a patch allowing this to be merged? It's currently causing problems with updating to next 14 in my project

**Comment by powderham** [comment]
For now I've forked it and am directly pointing to my own repo (not specifying a commit since i want master)

```
"nextjs-cors": "github:powderham/nextjs-cors",
```

**Comment by yonycalsin** [comment]
today I will try to publish the new version, thanks.

**Comment by yonycalsin** [comment]
next14 peer dependency support is now available in version 2.2.0.

https://github.com/yonycalsin/nextjs-cors/releases/tag/v2.2.0
